name: Deploy Website

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Node Modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: |
          cd 04-job-artifacts-events-cache
          npm ci
      - name: Lint code
        run: |
          cd 04-job-artifacts-events-cache
          npm run lint
      - name: Test code
        run: |
          cd 04-job-artifacts-events-cache
          npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      jsFiles: ${{ steps.publish.outputs.jsFiles }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Node Modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: |
          cd 04-job-artifacts-events-cache
          npm ci
      - name: Build website
        run: |
          cd 04-job-artifacts-events-cache
          npm run build
      - name: Publish Js fileName
        id: publish
        run: |
          cd 04-job-artifacts-events-cache
          echo "Publishing js files"
          find dist/assets/*.js -type f -execdir echo '::set-output name=jsFiles::{}' ';'
      - name: Archive website
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: section-4/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v4
        with:
          name: website
      - name: Show files
        run: ls -l
      - name: output js files
        run: echo ${{ needs.build.outputs.jsFiles }}
      - name: Deploy
        run: echo "Deploying website"
