name: environment-secrets

on:
  push:
    branches: ["dev", "stg"]

env:
  MONGODB_DB_NAME: "mongo-database"

jobs:
  test:
    environment: staging
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.d5xgm.mongodb.net
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          cd 05-environment-secrets
          npm ci
      - name: Run server
        run: |
          cd 05-environment-secrets
          npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: |
          cd 05-environment-secrets
          npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
