name: Output Metadata GitHub

on: workflow_dispatch

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: |
          echo "The event name is $GITHUB_EVENT_NAME, the repository is $GITHUB_REPOSITORY, and the workflow is $GITHUB_WORKFLOW."
          echo "${{ toJson(github) }}"
